on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-go@v2
        with:
          go-version: '^1.16.6'
      - run: make lint